export const TERMS_CONTENT = {
  effectiveDate: "Last updated: 10/11/2024",
  intro: `Please note that the following terms and conditions (the "Renit Terms and Conditions") govern your use of our websites (the "simplyenit.com", "renit.co.in"), application and the Services provided by us (collectively the “Platform”). By accessing or using our Platform, you agree to be bound by this agreement. If you do not agree with these terms and conditions, please refrain from using our Platform.`,
  "section1.1": `1.1. By accessing or using our Platform, you represent and warrant that you have read, understood, and agreed to be bound by these terms.`,
  "section1.2": `1.2. We reserve the right to modify or update these terms at any time without prior notice. It is your responsibility to review these terms periodically for any changes. Your continued use of our Platform after any modifications or updates constitutes your acceptance of the revised terms.`,
  "section2.1": `2.1. Use of the Platform is available only to persons who can form legally binding contracts under Indian Contract Act, 1872. Persons who are “incompetent to contract” within the meaning of the Indian Contract Act, 1872 including minors, un-discharged insolvents, etc. are not eligible to use the Platform. If you are a minor i.e. under the age of 18 years, you shall only use our Platform with the involvement of your parent or legal guardian.`,
  "section2.2": `2.2. You agree to comply with all applicable laws and regulations when using our Platform.`,
  "section3.1": `3.1. Renit is a rental marketplace that facilitates user-to-user product rentals. However, Renit (in its current version) does not process payments, manage logistics, or handle the physical exchange of products. Users must negotiate terms, arrange pick-up or drop-off logistics, and manage rental agreements directly through the our Platform’s ‘Chat’ feature, powered by Firebase.`,
  "section3.2": `3.2. Key Functionalities:
    4.1 Product Listing: Users can post products available for rent.
    4.2 Search and Discovery: Users can search and browse available products by category, location, and more.
    4.3 In-App Chat: Users connect and communicate through the chat feature.
    4.4 Location Tracking: Uses Google Location API to display relevant products based on proximity.
    4.5 Prohibited Products: You may only list products that are legal and do not infringe on third-party rights. Any illegal, dangerous, or otherwise restricted products are strictly prohibited.
    4.6 Guidelines: We prioritize transparency and reliability in our listings. We advise the owners/listers listing their products on our platform and the renters to conduct thorough checks and establish the authenticity of any product, property or service before proceeding with any transaction. Please adhere to the following guidelines:
      (a) Independent Verification: Users/potential renters should conduct comprehensive checks to verify the authenticity of the listed item including their suitability for buying or renting. This verification should be done at the user/potential renter’s own expense and in a manner deemed appropriate;
      (b) Renit’s Role: As an online marketplace and merely being an intermediary, Renit does not validate the authenticity of the listed products. Users/potential renters should be aware that content is uploaded by the listers/owners, and Renit does not filter or verify the same;
      (c) Ownership Verification: Users/potential renters are advised to conduct a comprehensive check of ownership to verify owners/lister’s credentials;
      (d) Personal Inspection: It is strongly recommended that users/potential renters personally inspect the listed products physically to ensure authenticity and existence of the listed item;
      (e) Beware of False Documents: As and when applicable the users/potential renters should exercise caution and conduct diligence regarding the required and valid documentation from the lister/owner;
      (f) Compliance with Regulations: As and when applicable the users/potential renters should independently ensure whether the lister/owner is complying with the provisions of all applicable laws; and
      (g) Please note that Renit serves as an intermediary platform and does not facilitate, negotiate, or assist in the rental transaction between the lister/owner and potential renters.
    While we rely on the information provided by listers for displaying listing items on our platform, users/potential renters are strongly encouraged to validate all information and review terms and conditions before making any decisions.
    4.7 Search Results: The ranking and display of products/listings in search results on the Platform depends on a variety of factors, including these main parameters:
      (a) User search parameters (eg. Number of products, destination, price range and other similar parameters);
      (b) Listing characteristics (eg. Location, price, calendar availability, number and quality of images, reviews, ratings and other quality signals); and
      (c) User experience (overall service, ease of booking and cancellation history of the owner/lister).`,
  "section4.1": `4.1. To use Renit’s Platform, you must create an Account. During registration, we collect the following information:
    • Personal Information: Includes name, email, phone number, address, and location.
    • Product Information: Details related to products listed, including photos (using camera access), descriptions, and tags (Only applicable if you decide to post a product or products on our Platform).
    You agree to provide accurate, complete, and up-to-date information. If you submit inaccurate or false information, Renit reserves the right to suspend or terminate your Account.
    You further agree that you shall be responsible for maintaining the confidentiality of your Account details and you shall be responsible for all activities that occur under your Account.`,
  "section4.2": `4.2. Data Collection: For details on our data practices, refer to our Privacy Policy.`,
  "section5.1": `5.1. You agree to provide accurate, current, and complete information when using our Platform.`,
  "section5.2": `5.2. You are solely responsible for any content you post on our Platform, including but not limited to products, chats that you have with different users and agree to comply with all applicable laws and regulations.`,
  "section5.3": `5.3. You must not post any false, misleading, or fraudulent information on our Platform.`,
  "section5.4": `5.4. You must not engage in any illegal activities or violate the rights of others when using our Platform.`,
  "section5.5": `5.5. In order to access certain features of our Platform, you may be required to create an Account. You are responsible for maintaining the confidentiality of your Account credentials and for all activities that occur under your Account.`,
  "section5.6": `5.6. You are solely responsible for your rental agreements, including pick-up, drop-off, product condition, and adherence to agreed rental terms.`,
  "section5.7": `5.7. You agree with not using the chat function to harass, spam, or abuse other users.`,
  "section5.8": `5.8. You shall not host, display, upload, publish or share any information which belongs to another person and to which you do not have any right.`,
  "section5.9": `5.9. You agree not to use any device, software or routine to interfere or attempt to interfere with the proper working of the Platform or any transaction being conducted on the Platform, or with any other person’s use of the Platform.`,
  "section6.1": `6.1. You retain ownership of the content you post on our Platform. However, by posting content (in all forms) on our Platform, you grant us a non-exclusive, worldwide, royalty-free license to use, copy, modify, distribute, and display that content.`,
  "section6.2": `6.2. The availability of products for rental is subject to change without notice. Accordingly, we do not guarantee the availability of the products.`,
  "section7.1": `7.1. You must not post any content on our Platform that (i) is illegal, defamatory, offensive, obscene, or infringing upon the rights of others, (ii) defames, abuses, harasses, stalks, threatens or otherwise violates privacy of others.`,
  "section7.2": `7.2. We reserve the right to remove any content that violates these terms or is deemed inappropriate, without prior notice or explanation.`,
  "section8.1": `8.1. Our Platform and its contents, including but not limited to text, graphics, logos, and software, are the exclusive property of our Platform’s owner and are protected by applicable intellectual property laws.`,
  "section8.2": `8.2. You may not reproduce, modify, distribute, or display any part of our Platform without prior written consent from our Platform owner. Unauthorized use, reproduction, or distribution of Renit’s intellectual property is strictly prohibited.`,
  "section9.1": `9.1. Our Platform is provided "as is" without any warranties, expressed or implied.`,
  "section9.2": `9.2. We do not guarantee the accuracy, reliability, or completeness of any content on our Platform, including products.`,
  "section9.3": `9.3. We are merely a platform or a medium connecting renters with owners/listers directly; and therefore, are not accountable or liable for any grievances or damages. Therefore, we shall not be liable for any direct, indirect, incidental, consequential, or punitive damages arising from your use of our Platform.`,
  "section9.4": `9.4. We do not guarantee that our Platform will be error-free or uninterrupted.`,
  "section10.1": `10.1. You acknowledge that Renit has no general obligation to monitor content provided by and stored on behalf of you, or to actively seek facts or circumstances indicating illegal activity or the incompatibility of content with the rights of third parties, these Terms. However, Renit reserves the right to carry out voluntary own-initiative investigations to detect, identify, and remove or disable access to illegal or incompatible content, and to take any necessary measures in accordance with these Terms.`,
  "section10.2": `10.2. You agree to cooperate with and assist Renit in good faith, and to provide Renit with such information and take such actions as may be reasonably requested by Renit with respect to any investigation undertaken by Renit regarding content on the Platform or the use or abuse of the Platform.`,
  "section10.3": `10.3. As part of its own initiative investigations and the review of the content, Renit uses various processes and tools to identify, review, and moderate your content. This may include human review, automated review, or a combination of both. If automated means have been used to review the content, and Renit has subsequently taken action with respect to that content, Renit will notify the user who posted the content of the use of automated means to the extent that legitimate interests of Renit and its users do not preclude such notice.`,
  "section10.4": `10.4. Renit is entitled to suspend the processing of such content for a reasonable period of time, if the user in question frequently submits notifications that are manifestly unfounded. Where appropriate, Renit will issue a warning prior to such a suspension. When deciding on a suspension, Renit will take into account all relevant facts and circumstances apparent from the information available to Renit, including (i) the amount, severity and frequency of unfounded notifications; (ii) the ratio of unfounded notifications to all notifications of the user; and (iii) the intentions pursued by the Notifier, insofar as they can be determined by Renit.`,
  "section11.1": `11.1. You agree to indemnify and hold us harmless from any claims, damages, or liabilities arising out of your use of our Platform or any violation of these terms.`,
  "section12.1": `12.1. Our Platform may contain links to third-party websites. We do not endorse or control the content on these websites and are not responsible for any damages or losses incurred from their use.`,
  "section12.2": `12.2. Renit integrates with third-party services, such as Google Location API for location tracking and Firebase for chat. We are not responsible for the practices of these third-party services and encourage users to review their terms and privacy policies.`,
  "section13.1": `13.1. We reserve the right to terminate or suspend your access to our Platform at any time, without prior notice, for any reason or no reason at all. If terminated, you may not access the Platform without our permission.`,
  "section14.1": `14.1. Renit Terms and Conditions shall be governed by and interpreted and construed in accordance with the laws of India. The place of jurisdiction shall be exclusively Udaipur, Rajasthan.`,
  "section15.1": `15.1. If You have any questions, concerns, or requests regarding Renit’s Terms and Conditions, please contact us at support@simplyrenit.com.
    You can also use Renit’s Official Social Media accounts to contact us for any questions, concerns, or requests:
    X (formerly Twitter): https://x.com/simplyrenit
    Facebook: https://www.facebook.com/simplyrenit/
    Instagram: https://www.instagram.com/simplyrenit/
    LinkedIn: https://in.linkedin.com/company/simplyrenit`,
  "section16.1": `16.1. In the event of any grievance pertaining to our Terms or practices involving the usage of data, the Grievance Redressal Officer may be contacted at the coordinates provided herein below:
    Grievance Redressal Officer:
    Name: Mr. Garvit Babel
    Designation: CEO
    Email: garvit@simplyrenit.com
    Address: 6-ga-6, Ram Singh Ki Badi, Hiran Magri, Sector-11, Udaipur, Rajasthan, Pin Code - 313001
    Phone: +91 72979 41741`,
};

export const PRIVACY_CONTENT = {
  effectiveDate: "Last Updated: 11/11/2024",
  intro: `At Renit, we value the privacy of our users and are committed to protecting their Personal Information. Renit’s Privacy Policy (“Policy”) outlines how Renit Classifieds LLP, a company incorporated under the laws of India, having its registered office at 6-GA-6, Sector 11 Hiran Magri, Udaipur City, Girwa, Rajasthan - 313001 (“we” / “us” / “our” / “Renit”) collects, uses, discloses, processes, transfers, stores and protects the information gathered from users of our websites (the "simplyenit.com", "renit.co.in") or our application or other platforms and services that we offer (collectively, “Platform”). We are committed to safeguarding the privacy and security of information supplied by every person accessing or using our Platform (“you” or “user”). By accessing or using our Platform, you acknowledge that you have read and understood the Policy and you agree to the practices described in this Policy. If you do not agree with this Policy, please refrain from using our Platform. You signify that you have read and understood this Policy. We further reserve the right to update or modify this Policy at any time without prior notice and all such changes will be effective immediately upon our posting the updated or modified Policy on the Platform. We will not be bound to inform you of any such modification. You are therefore encouraged to review this Policy each time you access or use the Platform. This Privacy Policy applies to all users of Renit across all platforms and locations, including India, the United States, the European Union, and any other jurisdiction. Our practices comply with the Indian Information Technology Act and international regulations such as GDPR (EU), CCPA and CPRA (California), and CalOPPA.`,
  definitions: {
    account: "A unique account created by the user to access our Platform.",
    device:
      "Any device that can access our Platform such as a computer, a cell phone, a smartphone or a digital tablet.",
    personalData: "Any information that is capable of identifying the user.",
    service: "The services in full or part, provided by our Platform.",
    serviceProvider:
      "Any natural or legal person who processes the data on behalf of Renit. It refers to third-party companies or individuals employed by Renit to facilitate the Platform, to perform services related to the Platform or to assist Renit in analysing how the Platform is used.",
    usageData:
      "Data collected automatically, either generated by the use of the Platform or from the Platform infrastructure itself (for example, the duration of a page visit).",
  },
  informationWeCollect: {
    personalData: `We may collect the following Personal Data from you: Contact Information: First name, last name, email address, postal address, phone number, business name, and other similar contact details. Account Information: Username, password, and other credentials used to access and manage your Account. We collect this information when you register for an Account, post a product, contact us, or interact with other renters, owners on our Platform in any way. GPS Location: We use Google Location API to help locate products based in user proximity, ensuring accurate and relevant results for users.`,
    nonPersonalInformation: `We also gather Non-Personal Information that does not directly identify you, such as: Cookies and Tracking Technologies: We may use cookies, web beacons, and other tracking technologies to gather information about your interactions with our Platform, including your browsing patterns and preferences. Log Files: Our servers automatically record certain information, such as your IP address, browser type, referring/exit pages, and operating system. Usage Data: Usage Data is collected automatically when using our Platform. Usage Data may include information such as your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Platform that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.`,
  },
  useOfInformation: {
    personalData: `We use the Personal Data we collect for the following purposes: To provide and personalize our Platform for you, in order to enhance your experience on our Platform. To manage your Account & your registration as a user of our Platform. The Personal Data you provide can give you access to different functionalities of the Platform that are available to you as a registered user. To facilitate the publication of products, communicating with you regarding your products or inquiries, responding to your requests or inquiries, providing you with details of potential customers and sending you important updates or promotional materials. To contact you by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as the Platform’s push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation. To provide you with news, newsletters, special offers and general information about services we offer (unless if you have opted not to receive such communications). To analyse and improve our Platform, services, and marketing efforts. To comply with legal obligations, resolve disputes, and enforce our policies.`,
    nonPersonalInformation: `We may use Non-Personal Information for various purposes, including: Analysing and enhancing our Platform’s functionality and performance. To analyse trends, administer our Platform, track user movements, and gather demographic information for internal purposes. Tailoring our marketing efforts and advertisements based on your browsing behaviour. Conducting research and analysis to improve our Platform and services.`,
  },
  sharingOfInformation: {
    serviceProviders: `We may share your Personal Data with trusted third parties who assist us in operating our Platform, conducting business activities, providing services on our behalf, digital marketing or for any similar services to provide you with various value-added services. These service providers are obligated to protect your information and can only use it to perform specific tasks on our behalf.`,
    legalRequirements: `We may disclose your Personal Information if required to do so by law, regulation, or legal process, or if we believe it is necessary to protect our rights, property, or safety, or the rights, property, or safety of others.`,
    affiliates: `We may share your information with our Affiliates, in which case we will require those Affiliates to honour this Policy. “Affiliates” include our parent company and any other subsidiaries, joint venture partners or other companies that we control or that are under common control with us.`,
    businessTransfers: `In the event of a merger, acquisition, or sale of our business or assets, your Personal Information may be transferred to the relevant third party as part of the transaction. We will notify you of any such change in ownership or control of your Personal Information.`,
  },
  retentionOfData: `Renit will retain your Personal Data only for as long as is necessary for the purposes set out in this Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies. Renit will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of our Platform, or we are legally obligated to retain this data for longer time periods.`,
  transferOfData: `Your information, including Personal Data, is processed at Renit’s operating offices and in any other place where the parties involved in the processing are located. It means that this information may be transferred to - and maintained on - computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from your jurisdiction. Your consent to this Policy followed by your submission of such information represents your agreement to that transfer. Renit will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other Personal Information.`,
  deleteYourData: `You have the right to delete or request that we assist in deleting the Personal Data that we have collected about you. Our Platform may give you the ability to delete certain information about you from within the Platform. You may update, amend, or delete your information at any time by signing in to your Account, if you have one, and visiting the ‘Profile’ section that allows you to manage your Personal Information. You may also contact us to request access to, correct, or delete any Personal Information that you have provided to us. Please note, however, that we may need to retain certain information when we have a legal obligation or lawful basis to do so.`,
  dataSecurity: `We take reasonable measures to protect your Personal Information from unauthorized access, disclosure, alteration, or destruction. We use industry-standard security techniques, including encryption, firewalls, and secure socket layer technology (SSL), to safeguard your data. However, please note that no method of transmission over the internet or electronic storage is completely secure, and we cannot guarantee absolute security.`,
  otherGeneralRights: `You have certain rights regarding the Personal Information we hold about you. These rights may include: Access: You can request a copy of the information we hold about you. Rectification: You can request to correct or update your information if it is inaccurate or incomplete. You can always opt-out of receiving further promotional correspondence from us or our Affiliates.`,
  euResidents: {
    gdprCompliance: `This section provides additional information regarding Renit’s processing of Personal Data of people located in the European Union. For the purposes of this section, “Personal Data” has the definition set forth in the General Data Protection Regulations (“GDPR”).`,
    legalBasis: `Our legal basis for processing Personal Data depends on the context in which we process it. We process Personal Data from you where we need it to perform a contract with you, where the processing is in our legitimate interests (including the purposes described in this Policy), where the processing is necessary for us to meet our applicable legal obligations, or if we otherwise have your consent.`,
    specialCategoryData: `Renit does not intend to collect any Special Category Data, which is any data that reveals your racial or ethnic origin, political opinions, religious, moral or philosophical beliefs, trade union membership, political views, the processing of genetic data, biometric data for the purpose of identifying a person, and data concerning health or a person’s sex life and/or sexual orientation. Please refrain from sending us any Special Category Data.`,
    rights: `You can exercise any of the rights set out under the GDPR, including: Withdraw Consent: You may withdraw your consent to data collection. However, you must note, this is possible only after you delete your Account which would ensure an erasure of your data. Data Portability: Request transfer of your data in a machine-readable format.`,
  },
  californiaResidents: {
    ccpaCompliance: `This section applies to our collection and use of Personal Information if you are a resident of California, as required by the California Consumer Privacy Act of 2018 and its implementing regulations, amended by the California Privacy Rights Act (“CRPA”) (collectively as “CCPA”).`,
    personalInformation: `We collect Personal Information as mentioned in Section 2.1 above. (Personal Data).`,
    useOfPersonalInformation: `We collect Personal Information for the business and commercial purposes detailed in Section 3 (Use of Information) above.`,
    sharingOfPersonalInformation: `We may share your Personal Information with the entities set out in Section 4 (Sharing of Information) above.`,
    rights: `You can exercise any of the rights set out under the CCPA, including: Opt-Out of Sale: Though we don’t sell Personal Information, you may contact us if you wish to opt-out of future data sharing with third parties. Right to Know and Delete: Request details of Personal Data collected and deletion of data.`,
  },
  childrensPrivacy: `If you’re under the age of 18, you may use our Platform only with the involvement of a parent or guardian. However, our Platform is not intended for use by individuals under the age of 13. We do not knowingly collect Personal Information from anyone under the age of 13. If you believe we have unintentionally collected information from a child, please contact us immediately, and we will take steps to remove that information from our systems. If you are a parent or guardian and you are aware that your child has provided us with Personal Data, please contact us to get it removed.`,
  changesToPolicy: `We reserve the right to modify or update the Policy at any time. Any changes will be effective upon posting the revised Policy on our Platform. We encourage you to review the Policy periodically for any updates. Your continued use of our Platform after any modifications or updates constitutes your acceptance of the revised Policy.`,
  contactUs: `If you have any questions, concerns, or requests regarding the Policy or the handling of your information, please contact us at support@simplyrenit.com. You can also use the following Renit’s Official Social Media accounts to contact us for any questions, concerns, or requests: X (formerly Twitter): https://x.com/simplyrenit Facebook: https://www.facebook.com/simplyrenit/ Instagram: https://www.instagram.com/simplyrenit/ LinkedIn: https://in.linkedin.com/company/simplyrenit`,
  grievanceRedressalOfficer: {
    name: "Mr. Garvit",
    email: "garvit@simplyrenit.com",
    address:
      "6-ga-6, Ram Singh Ki Badi, Hiran Magri, Sector-11, Udaipur, Rajasthan, Pin Code - 313001",
  },
};
